### ISSUE TITLE
v1.2.0 published corrupted NPM package

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/graphgen#9]
If you look at the archive the only file in `dist/` is `dist/index.js`, no type information, no source maps or anything. Not sure what's going on, but package is developed with NPM, not yarn, and looks like `prepack` script is running twice, once under yarn, again with npm.

https://unpkg.com/browse/@frontside/graphgen@1.2.0/dist/

Here is the release action run https://github.com/thefrontside/graphgen/runs/5131947074?check_suite_focus=true

**Comment by minkimcello** [comment]
https://unpkg.com/browse/@frontside/graphgen@1.2.2/dist/
